# This is an example of a Kubernetes Deployment that consumes the
# configuration from the 'my-app-config' ConfigMap.
#
# To apply this: kubectl apply -f deployment.yaml
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
  namespace: my-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
      - name: example-service-container
        # Replace this with the actual image you would build from the example
        image: your-registry/example-service:latest
        ports:
        - containerPort: 8080
        
        # This 'envFrom' block is the key part.
        # It tells Kubernetes to load all key-value pairs from the specified
        # ConfigMap and inject them as environment variables into this container.
        envFrom:
        - configMapRef:
            name: my-app-config
        
        # You can still define other environment variables as needed.
        # Note that OBS_SERVICE_NAME is set here directly, as it's specific
        # to this service and not shared in the common ConfigMap.
        env:
        - name: OBS_SERVICE_NAME
          value: "example-service"
